defaults:
  - _self_
  - robot: unitree_g1_29dof

project_name: "MRlib"
exp_name: &exp_name mrlib_retarget
headless: True
seed: 0
output_path: output
rl_device: "cuda:0"
device: "cuda"
device_id: 0
train: True

hydra:
  job:
    name: ${exp_name}
    env_set:
      OMP_NUM_THREADS: 1
  run:
    dir: output

